Repository wecode-bootcamp-korea/29-2nd-needed-frontend, pull requests merged in 2022-02, with the labels that each got.

#1 [29기 곽승현] Add : Footer에 jsx, styled-components를 추가함
  package-lock.json
  package.json
  public/images/logo-wide.png
  public/index.html
  src/components/Footer/Footer.js
  src/components/Nav/Nav.js
Labels: Status: 리뷰 요청

#2 [29기 윤남주] JobList 컴포넌트 레이아웃 구현
  src/Router.js
  src/components/Buttons/FilterButton.js
  src/components/Buttons/SortButton.js
  src/components/JobCard/JobCard.js
  src/components/Modals/LOCATION_DATA.js
  src/components/Modals/LocationModal.js
  src/components/Modals/LocationModalComponents/LocationModalHeader.js
  src/components/Modals/LocationModalComponents/LocationModalList.js
  src/components/Modals/LocationModalComponents/LocationModalSelectBox.js
  src/components/Modals/SortModal.js
  src/components/Modals/YearsModal.js
  src/pages/JobList/JOB_LIST_DATA.js
  src/pages/JobList/JobList.js
  src/pages/JobList/JobListFilter.js
  src/pages/JobList/JobListHeader.js
Labels: Status: Accepted

#3 [29기 장예지] Nav layout
  public/images/nav/menu.png
  public/images/nav/needed.png
  public/images/nav/search.png
  src/components/Nav/Nav.js
  src/components/Nav/SIDEBAR_INSIDE.js
  src/components/Nav/SideInside.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#9 [29기 장예지] nav postion 수정
  src/components/Nav/Nav.js
  src/components/Nav/SIDEBAR_INSIDE.js
  src/components/Nav/SideInside.js
Labels: Status: 리뷰 요청

#5 [29기 윤남주] JobDetail 컴포넌트 구현
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/Router.js
  src/pages/JobDetail/JOB_DETAIL_MOCK.js
  src/pages/JobDetail/JobDetail.js
  src/pages/JobDetail/JobDetailApplicationForm.js
  src/pages/JobDetail/JobDetailApply.js
  src/pages/JobDetail/JobDetailApplyRender.js
  src/pages/JobDetail/JobDetailCompany.js
  src/pages/JobDetail/JobDetailContent.js
  src/pages/JobDetail/JobDetailHeader.js
  src/pages/JobDetail/JobDetailInfo.js
  src/pages/JobDetail/JobDetailRegulation.js
  src/pages/JobDetail/JobDetailShareModal.js
  src/pages/JobDetail/Map.js
  src/pages/JobList/JOB_LIST_DATA.js
Labels: Status: 리뷰 요청

#13 [29기 장예지] Feature/nav display 수정
  src/components/Nav/Nav.js
  src/components/Nav/SIDEBAR_INSIDE.js
Labels: Status: Rebase 요청

#7 [29기 곽승현] Add : Company.js의 룩을 구현하고, 코드의 가독성을 위해 컴포넌트를 분리하고, 컨플릭트를 해결했습니다.
  public/data/COMPANY_DATA.json
  public/data/JOB_LISTINGS.json
  src/Router.js
  src/pages/Company/Company.js
  src/pages/Company/components/Card.js
  src/pages/Company/components/Chip.js
  src/pages/Company/components/CompanyAside.js
  src/pages/Company/components/CompanyHead.js
  src/pages/Company/components/CompanyInfo.js
Labels: Status: 리뷰 요청

#11 [29기 곽승현] Add : 직군별 연봉 페이지의 룩을 구현하고, 기본적인 기능들을 구현함
  package-lock.json
  package.json
  public/data/salarySelect.json
  src/Router.js
  src/pages/Salary/Salary.js
  src/pages/Salary/components/GraphComponent.js
Labels: Status: Accepted

#12 [29기 윤남주] MyPage 컴포넌트 구현
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/site.webmanifest
  src/Router.js
  src/pages/MyPage/ApplicationStatusBlock.js
  src/pages/MyPage/EditProfession.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPageApplication.js
  src/pages/MyPage/MyPagePersonal.js
  src/pages/MyPage/MyPagePersonalEditModal.js
  src/pages/MyPage/MyPageProfession.js
  src/pages/MyPage/PROFESSION_CATEGORY.js
Labels: Status: 리뷰 요청

#15 [29기 곽승현] Add : WantedPlusContents.js 페이지의 룩 구현
  public/data/plusContents.json
  public/images/neededPlusPurple.png
  public/images/neededPlusWhite.png
  public/images/thumb-up-dynamic-color.png
  src/Router.js
  src/pages/WantedPlus/WantedPlus.js
  src/pages/WantedPlus/WantedPlusContents.js
  src/pages/WantedPlus/WantedPlusLanding.js
  src/pages/WantedPlus/components/PlusCard.js
Labels: Status: 리뷰 요청

#14 [29기 윤남주] JobList 필터링 구현 + 백엔드 통신
  package-lock.json
  package.json
  src/components/Buttons/FilterButton.js
  src/components/Buttons/SortButton.js
  src/components/JobCard/JobCard.js
  src/components/Modals/LOCATION_DATA.js
  src/components/Modals/LocationModal.js
  src/components/Modals/LocationModalComponents/LocationModalHeader.js
  src/components/Modals/LocationModalComponents/LocationModalList.js
  src/components/Modals/QUERY_EXCHANGE.js
  src/components/Modals/SortModal.js
  src/pages/JobList/JOB_LIST_DATA.js
  src/pages/JobList/JobList.js
  src/pages/JobList/JobListFilter.js
  src/pages/JobList/JobListHeader.js
  src/pages/JobList/searchParam.js
Labels: Status: 리뷰 요청

#19 [29기 윤남주] MyPage 백엔드 통신 + 프로필 정보 업데이트 기능 구현
  src/api/config.js
  src/pages/JobList/JOB_LIST_DATA.js
  src/pages/JobList/JobList.js
  src/pages/MyPage/EditProfession.js
  src/pages/MyPage/MYPAGE_IDS.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPageApplication.js
  src/pages/MyPage/MyPagePersonal.js
  src/pages/MyPage/MyPagePersonalEditModal.js
  src/pages/MyPage/MyPageProfession.js
  src/pages/MyPage/PROFESSION_CATEGORY.js
Labels: Status: 리뷰 요청

#21 [29기 곽승현] Refactor : Changed misc errors, fetched data from back in Salary.js
  src/Router.js
  src/components/Footer/Footer.js
  src/pages/Company/Company.js
  src/pages/Company/components/Chip.js
  src/pages/Company/components/CompanyAside.js
  src/pages/Company/components/CompanyHead.js
  src/pages/Company/components/CompanyInfo.js
  src/pages/Salary/Salary.js
  src/pages/Salary/components/GraphComponent.js
  src/pages/WantedPlus/WantedPlusLanding.js
Labels: Status: 리뷰 요청

#4 [29기 박무선] 메인 페이지 레이아웃 & 이미지 슬라이더 기본 레이아웃
  package-lock.json
  public/data/data1.json
  public/data/data2.json
  public/images/banner1.jpeg
  public/images/banner2.jpeg
  public/images/banner3.jpeg
  public/images/banner4.jpeg
  public/images/banner5.jpeg
  public/images/banner6.jpeg
  public/images/banner7.jpeg
  public/images/class1.jpeg
  public/images/class2.jpeg
  public/images/class3.jpeg
  public/images/class4.jpeg
  public/images/ipad.png
  public/images/office_pic.png
  public/images/vod1.jpeg
  public/images/vod2.jpeg
  public/images/vod3.jpeg
  public/images/vod4.jpeg
  public/images/vod5.jpeg
  public/images/vod6.jpeg
  public/index.html
  src/Router.js
  src/pages/Main/BANNERS_DATA.js
  src/pages/Main/BannerItem/BannerItem.js
  src/pages/Main/ImageSlider/BANNER_DATAS.js
  src/pages/Main/ImageSlider/BannerSlider.js
  src/pages/Main/ImageSlider/EVENT_DATAS.js
  src/pages/Main/ImageSlider/EventSlider.js
  src/pages/Main/ImageSlider/VOD_DATAS.js
  src/pages/Main/ImageSlider/VodSlider.js
  src/pages/Main/JOB_INFOS.js
  src/pages/Main/JobInfo/JobInfo.js
  src/pages/Main/Main.js
  src/pages/Resume/Resume.js
Labels: Status: 리뷰 요청

#20 [29기 윤남주] JobDetail 백엔드 통신
  src/Router.js
  src/api/config.js
  src/components/Buttons/FilterButton.js
  src/components/JobCard/JobCard.js
  src/components/Modals/LocationModal.js
  src/components/ScrollToTop.js
  src/pages/JobDetail/JobDetail.js
  src/pages/JobDetail/JobDetailApplicationForm.js
  src/pages/JobDetail/JobDetailApply.js
  src/pages/JobDetail/JobDetailApplyRender.js
  src/pages/JobDetail/JobDetailCompany.js
  src/pages/JobDetail/JobDetailContent.js
  src/pages/JobDetail/JobDetailHeader.js
  src/pages/JobDetail/JobDetailInfo.js
  src/pages/JobDetail/JobDetailRegulation.js
  src/pages/JobList/JobList.js
Labels: Status: 리뷰 요청

#22 [29기 장예지] 로그인 modal 수정 & config
  src/components/Nav/Nav.js
  src/pages/Login/Login.js
  src/pages/Login/SignUp.js
Labels: Status: Accepted

#24 [29기 윤남주] 버그 수정
  public/index.html
Labels: Status: 리뷰 요청

#27 [29기 윤남주] 이력서 업로드 API주소, 토큰 변경
  src/pages/Main/ImageSlider/BannerSlider.js
  src/pages/Main/Main.js
  src/pages/MyPage/MyPageApplication.js
  src/pages/Resume/Components/ResumeDocuments.js
  src/pages/Resume/Components/ResumeFiles.js
Labels: Status: 리뷰 요청

#28 [29기 장예지] nav 수정
  src/components/Nav/Nav.js
  src/pages/Login/Login.js
Labels: Status: 리뷰 요청
